# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Build

on:
- push

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-latest
        - macos-latest
        - ubuntu-latest
        go:
        - "1.27"

      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version: ${{ matrix.go }}

    - name: Setup FFmpeg on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -q -q
        sudo apt-get install --yes ffmpeg

    - name: Setup FFmpeg on macOS
      if: runner.os == 'macOS'
      run: brew install ffmpeg

    - name: Setup FFmpeg on Windows
      if: runner.os == 'Windows'
      run: choco install ffmpeg

    - name: Run FFmpeg
      run: ffmpeg -version

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
